### ISSUE TITLE
Brave doesn't load properly

### ISSUE THREAD

**Issue by FreeBornAngel** [fernandosoder/Hivetasks#1]
I have to dump the cookie from the browser each time I change accounts.

The page doesn't load until the cookie has been deleted.
Then it will reload to change from hive.blog to peakd.
If I try to reload again, it goes to a blank screen.

**Comment by fernandosoder** [comment]
That's strange as the website doesn't use cookies, just ``localStorage`` from Javascript to set configuration and no cookies are set by the program.

Could you provide more details, like filming yourself accessing the website so I can see where is the problem.

Main File: https://github.com/fernandosoder/Hivetasks/blob/master/sw_clone/res/js/sw.out.min.js
